########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
  - test
  - doc

########
# Test #
###############################################################################
test:
  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
  stage: test
  script:
    - python3 scripts/build.py
    - py.test -v engine/test

#################
# Gitlab pages  #
###############################################################################
pages:
  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
  stage: doc
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - mkdocs build -f scripts/mkdocs.yml -d public

  only:
    - master

  artifacts:
    paths:
      - public