########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
  - docker_image
  - test
  - doc

################
# Docker image #
###############################################################################
docker_image:
  stage: docker_build
  image: docker:latest

  services:
    - docker:dind

  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME ./scripts/docker/build_ci
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

########
# Test #
###############################################################################
test:
  image: $CI_REGISTRY/cyberegoorg/cetech:master
  stage: test
  script:
    - python3 scripts/build.py
    #- py.test -v engine/tests/

#################
# Gitlab pages  #
###############################################################################
pages:
  image: $CI_REGISTRY/cyberegoorg/cetech:master
  stage: doc
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - mkdocs build -f scripts/mkdocs.yml -d public

  only:
    - master

  artifacts:
    paths:
      - public