########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
 - test
 - doc

########
# Test #
###############################################################################
test:
  image: ondravoves/cetech:build_ci
  stage: test
  script:
  - pip install -r scripts/dev_requirements.txt
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
  - make -j 4
  #- py.test -v engine/tests/

#################
# Gitlab pages  #
###############################################################################
pages:
  image: ondravoves/debian:python2.7
  stage: doc
  script:
  - pip install mkdocs mkdocs-bootswatch
  - mkdocs build -f scripts/mkdocs.yml -d public

  only:
    - master

  artifacts:
    paths:
    - public