########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
# - test
 - doc

########
# Test #
###############################################################################
#test:
#  image: ondravoves/cetech:build_ci
#  stage: test
#  script:
#  - mkdir build
#  - cd build
#  - cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Develop
#  - make -j 4
#  - ./cetech_tests

#################
# Gitlab pages  #
###############################################################################
pages:
  image: ondravoves/debian:python2.7
  stage: doc
  script:
  - pip install mkdocs mkdocs-bootswatch
  - cd docs/basic
  - mkdocs build -d ../../public/basic
  - cd ../lua_api
  - mkdocs build -d ../../public/lua_api

  only:
    - master

  artifacts:
    paths:
    - public