########
# Core #
###############################################################################

##########
# Stages #
###############################################################################
stages:
 - test
 - doc

########
# Test #
###############################################################################
test:
  image: ondravoves/cetech:build_ci
  stage: test
  script:
  - python3 scripts/build.py
  #- py.test -v engine/tests/

#################
# Gitlab pages  #
###############################################################################
pages:
  image: ondravoves/cetech:build_ci
  stage: doc
  script:
  - mkdocs build -f scripts/mkdocs.yml -d public

  only:
    - master

  artifacts:
    paths:
    - public