########
# Core #
###############################################################################
variables:
  GIT_SUBMODULE_STRATEGY: recursive

##########
# Stages #
###############################################################################
stages:
  - build
  - test
  - doc

########
# Build #
###############################################################################
build:
  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
  stage: build

  artifacts:
    paths:
      - bin

  script:
    - python3 scripts/build.py


########
# Test #
###############################################################################
#test:
#  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
#  stage: test
#  variables:
#    SDL_VIDEODRIVER: dummy
#
#  dependencies:
#    - build
#
#  script:
#    - py.test -v --color=yes engine/test

#################
# Gitlab pages  #
###############################################################################
pages:
  image: $CI_REGISTRY/cyberegoorg/cetech-docker-toolchain:master
  stage: doc
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - mkdocs build -f scripts/mkdocs.yml -d public

  only:
    - master

  artifacts:
    paths:
      - public