######s##
# Core #
###############################################################################
image: ondravoves/debian:python2.7

##########
# Stages #
###############################################################################
stages:
  - doc

#################
# Gitlab pages  #
###############################################################################
pages:
  stage: doc
  script:
  - pip install mkdocs
  - mkdocs build -d public

  only:
    - master

  artifacts:
    paths:
    - public