language: python

sudo: false

python:
  - "3.5"

cache:
  apt: true
  pip: true
  directories:
  - ./externals/src

addons:
  apt:
    sources:
      - mono
    packages:
      - mono-complete

install:
  - pip install -r requirements.txt
  #- python externals/externals.py
  - python build.py -d

script:
  - sources/CETech/bin/Linux/AnyCPU/Debug/NSpecRunner.exe sources/CETech/bin/Linux/AnyCPU/Debug/CETechDevelopTest.dll
