language: c++
compiler: clang

clang:
  - "3.7"

branches:
  only:
    - master

os:
  - linux

cache:
  - pip

  - directories:
    - ./external/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

    packages:
      - make
      - libtool
      - automake
      - time
      - python3

install:
  - clang --version
  - python3 --version
  - pip install -r requirements.txt
  - python3 ./external.py
  - python3 ./make.py


script:
 - ./.build/linux64_clang/bin/cetech_testDebug

