language: cpp
compiler: clang

branches:
  only:
    - master

os:
  - linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3.5 gcc make libtool automake
  - python3.5 ./external.py
  - python3.5 ./make.py

script:
 - ./.build/linux64_clang/bin/cetech_testDebug

