language: cpp

compiler: clang
python: "3.5"
clang: "3.7"

before_install:
  - clang --version
  - pip install -r requirements.txt

install:
  - python3 ./external.py
  - python3 ./make.py

script: ./.build/linux64_clang/bin/cetech_testDebug
