language: cpp
compiler: clang

branches:
  only:
    - master

os:
  - linux

python:
  - "3.5"

addons:
  apt:
    packages:
      - gcc
      - make
      - libtool
      - automake
      - time

install:
  - python3.5 ./external.py
  - python3.5 ./make.py

script:
 - ./.build/linux64_clang/bin/cetech_testDebug

