language: cpp

sudo: false

branches:
  only:
    - master

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

    packages:
      - clang-3.7
      - gcc
      - make
      - libtool
      - automake
      - python3.5
      - time

install:
  - python3.5 ./external.py
  - python3.5 ./make.py

cache:
  directories:
    - external

script:
 - ./.build/linux64_clang/bin/cetech_testDebug

