language: cpp

os:
  - linux

addons:
  apt:
    packages:
      - clang-3.6
      - python3
      - python3-yaml
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

before_install:
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 100
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100
  - clang --version

install:
  - python3 ./external.py
  - python3 ./make.py

script: ./.build/linux64_clang/bin/cetech_testDebug

