language: python

sudo: false

python:
  - "3.5"

cache:
  apt: true
  pip: true
  directories:
  - ./external/

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
    packages: ['clang-3.7', 'libboost-all-dev']
env: COMPILER=clang++-3.7

install:
  - pip install pyyaml
  - python externals.py -v
  - python make.py --cxx=$COMPILER

script:
  - ./.build/linux64_clang/bin/cetech_testDebug
