language: python

python:
  - "3.5"

branches:
  only:
    - master

os:
  - linux

cache:
  pip: true
  apt: true
  directories:
  - ./external/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

    packages:
      - make
      - libtool
      - automake
      - time
      - clang-3.7

install:
  - clang --version
  - pip install -r requirements.txt
  - python ./external.py
  - python ./make.py


script:
 - ./.build/linux64_clang/bin/cetech_testDebug

