language: cpp

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['python3.5', 'cython3', 'python3-yaml']

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7

install:
  - python3.5 external.py

script:
  python make.py --cxx=$COMPILER