language: python

sudo: false

branches:
  only:
    - master

os:
  - linux

python:
  - "3.5"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

    packages:
      - clang-3.7
      - gcc
      - make
      - libtool
      - automake
      - time

install:
  - python --version
  - python ./external.py
  - python ./make.py

cache:
  directories:
    - external

script:
 - ./.build/linux64_clang/bin/cetech_testDebug

