language: python

sudo: false

branches:
  only:
    - master

os:
  - linux

python:
  - "3.5"

cache:
  - pip

  - directories:
    - external

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise

    packages:
      - clang-3.7
      - g++
      - make
      - libtool
      - automake
      - time

install:
  - clang --version
  - python --version
  - pip install -r requirements.txt
  - python ./external.py
  - python ./make.py


script:
 - ./.build/linux64_clang/bin/cetech_testDebug

