language: python

python:
  - "3.5"

sudo: false

cache:
  apt: true
  pip: true
  directories:
  - ./external/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']

      install:
        - pip install pyyaml
        - python external.py
        - python make.py --cxx=clang++-3.7

      script:
        - ./.build/linux64_clang/bin/cetech_testDebug
