language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'python3.5', 'cython3', 'python3-yaml']
      env: COMPILER=clang++-3.7

install:
  - python3.5 external.py
  - python3.5 make.py --cxx=$COMPILER

script:
  - ./.build/linux64_clang/bin/cetech_testDebug