language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
           - BUILD_TYPE='Release'
           - LLVM_VERSION=3.8.0
           - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
           - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
           - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
           - CXXFLAGS=-lc++
           - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH

    - os: linux
      compiler: clang
      env:
           - BUILD_TYPE='Debug'
           - LLVM_VERSION=3.8.0
           - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
           - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
           - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
           - CXXFLAGS=-lc++
           - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake
    fi
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang-$LLVM_VERSION
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make -j 2
  - ctest -V -j 2
