site_name: CETech
site_author: Ondra Voves

repo_url: https://github.com/cyberegoorg/cetech
theme: readthedocs

pages:
  - Úvod: 'index.md'
  - Architektůra: 'architecture/overview.md'
  - New Game: 'new_game/overview.md'

  - Engine:
    - Popis: 'engine/overview.md'
    - Build: 'engine/build.md'

  - Playground:
    - Popis: 'playground/overview.md'
    - Historie v obrázcích: 'playground/image_history.md'

  - API C++:
    - log: 'engine/api/cpp/log.md'

  - API Lua:
    - Application: 'engine/api/lua/application.md'
    - Package: 'engine/api/lua/package.md'
    - Keyboard: 'engine/api/lua/keyboard.md'
    - Mouse: 'engine/api/lua/mouse.md'
    - Vector2: 'engine/api/lua/vector2.md'
    - Vector3: 'engine/api/lua/vector3.md'

  - About:
    - Poznámky k vydání: 'about/release-notes.md'
    - Licence: 'about/license.md'

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
