site_name: CETech
site_author: Ondra Voves

repo_url: https://github.com/cyberegoorg/cetech
theme: readthedocs

pages:
  - CETech: 'index.md'

  - Engine:
    - Overview: 'engine/overview.md'
    - Build: 'engine/build.md'

  - Playground:
    - Overview: 'playground/overview.md'
    - Images: 'playground/image_history.md'

  - Lua API:
      - Log: 'lua_api/Log.md'
      - Application: 'lua_api/Application.md'
      - Package: 'lua_api/PackageManager.md'
      - Keyboard: 'lua_api/Keyboard.md'
      - Mouse: 'lua_api/Mouse.md'

  - About:
    - Release notes: 'about/release-notes.md'
    - Licence: 'about/license.md'
    - 3rd party: 'about/3rdparty.md'

markdown_extensions:
    - admonition
    - codehilite(css_class=code)
    - toc:
        permalink: '#'