site_name: CETech LUA api
site_author: Ondra Voves

repo_url: https://gitlab.com/cyberegoorg/cetech
theme: slate

pages:
  - Lua API: 'index.md'
  - Core:
    - cetech.Log: 'Log.md'
    - cetech.Application: 'Application.md'
    - cetech.Package: 'Package.md'
    - cetech.World: 'World.md'
    - cetech.Unit: 'Unit.md'

  - Input:
    - cetech.Keyboard: 'Keyboard.md'
    - cetech.Mouse: 'Mouse.md'
    - cetech.Gamepad: 'Gamepad.md'

  - Components:
    - cetech.Transform: 'Transform.md'
    - cetech.Camera: 'Camera.md'

markdown_extensions:
    - admonition
    - codehilite(noclasses=true,pygments_style=tango)
    - toc:
        permalink: '#'