version: 0
blobs:
    - name: renderconfig
      guard_prefix: CETECH

      values:
        - uint32_t global_resource_count
        - uint32_t local_resource_count
        - uint32_t layer_count
        - uint32_t layer_entry_count
        - uint32_t viewport_count

        - render_resource_t global_resource[global_resource_count]
        - render_resource_t local_resource[local_resource_count]
        - uint64_t layers_name[layer_count]
        - uint32_t layers_entry_count[layer_count]
        - uint32_t layers_entry_offset[layer_count]
        - uint32_t layers_localresource_count[layer_count]
        - uint32_t layers_localresource_offset[layer_count]
        - layer_entry_t layers_entry[layer_entry_count]
        - viewport_entry_t viewport[viewport_count]
