site_name: CETech
site_author: Ondra Voves

repo_url: https://gitlab.com/cyberegoorg/cetech
theme: readthedocs
#theme: alabaster


markdown_extensions:
    - admonition
    #- codehilite(noclasses=true,pygments_style=tango)
    - toc:
        permalink: '#'

pages:
  - CETech: 'index.md'

  - About:
    - Release notes: 'about/release-notes.md'
    - Licence: 'about/license.md'
    - 3rd party: 'about/3rdparty.md'

  - Engine:
    - Overview: 'engine/overview.md'
    - Build: 'engine/build.md'
    - Resource: 'engine/resource.md'

  - Playground:
    - Overview: 'playground/overview.md'
    - Images: 'playground/image_history.md'

  - Examples:
    - 00-minimal: 'examples/00-minimal.md'

  - Lua API: 'lua_api.md'