version: 1

formatters:
  colored:
      (): 'colorlog.ColoredFormatter'
      format: "%(log_color)s---\nlevel: %(levelname)s\nwhere: %(name)s\ntime: %(asctime)s\nworker: %(process)d\nmsg: |\n   %(message)s"
      log_colors:
        DEBUG:    'green'
        INFO:     'blue'
        WARNING:  'yellow'
        ERROR:    'red'
        CRITICAL: 'red'

  yaml:
      format: "---\nlevel: %(levelname)s\nwhere: %(name)s\ntime: %(asctime)s\nworker: %(process)d\nmsg: |\n   %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: colored
        stream: ext://sys.stdout

    file:
        class: logging.handlers.TimedRotatingFileHandler
        formatter: yaml
        filename: playground_log.yml
        when: d

root:
    level: DEBUG
    handlers: [console, file]

loggers:
  aiohttp:
      level: DEBUG

  nanoreq:
      level: ERROR
